module.exports = {
  isDate: require("date-fns/isDate").default,
  isValidDate: require("date-fns/isValid").default,
  format: require("date-fns/format").default,
  addMinutes: require("date-fns/addMinutes").default,
  addHours: require("date-fns/addHours").default,
  addDays: require("date-fns/addDays").default,
  addWeeks: require("date-fns/addWeeks").default,
  addMonths: require("date-fns/addMonths").default,
  addYears: require("date-fns/addYears").default,
  addQuarters: require("date-fns/addQuarters").default,
  subMinutes: require("date-fns/subMinutes").default,
  subHours: require("date-fns/subHours").default,
  subDays: require("date-fns/subDays").default,
  subWeeks: require("date-fns/subWeeks").default,
  subMonths: require("date-fns/subMonths").default,
  subYears: require("date-fns/subYears").default,
  getSeconds: require("date-fns/getSeconds").default,
  getMinutes: require("date-fns/getMinutes").default,
  getHours: require("date-fns/getHours").default,
  getDay: require("date-fns/getDay").default,
  getDate: require("date-fns/getDate").default,
  getISOWeek: require("date-fns/getISOWeek").default,
  getMonth: require("date-fns/getMonth").default,
  getQuarter: require("date-fns/getQuarter").default,
  getYear: require("date-fns/getYear").default,
  getTime: require("date-fns/getTime").default,
  setSeconds: require("date-fns/setSeconds").default,
  setMinutes: require("date-fns/setMinutes").default,
  setHours: require("date-fns/setHours").default,
  setMonth: require("date-fns/setMonth").default,
  setQuarter: require("date-fns/setQuarter").default,
  setYear: require("date-fns/setYear").default,
  min: require("date-fns/min").default,
  max: require("date-fns/max").default,
  differenceInCalendarDays: require("date-fns/differenceInCalendarDays")
    .default,
  differenceInCalendarMonths: require("date-fns/differenceInCalendarMonths")
    .default,
  differenceInCalendarWeeks: require("date-fns/differenceInCalendarWeeks")
    .default,
  differenceInCalendarYears: require("date-fns/differenceInCalendarYears")
    .default,
  startOfDay: require("date-fns/startOfDay").default,
  startOfWeek: require("date-fns/startOfWeek").default,
  startOfMonth: require("date-fns/startOfMonth").default,
  startOfQuarter: require("date-fns/startOfQuarter").default,
  startOfYear: require("date-fns/startOfYear").default,
  endOfDay: require("date-fns/endOfDay").default,
  endOfWeek: require("date-fns/endOfWeek").default,
  endOfMonth: require("date-fns/endOfMonth").default,
  isEqual: require("date-fns/isEqual").default,
  isSameDay: require("date-fns/isSameDay").default,
  isSameMonth: require("date-fns/isSameMonth").default,
  isSameYear: require("date-fns/isSameYear").default,
  isSameQuarter: require("date-fns/isSameQuarter").default,
  isAfter: require("date-fns/isAfter").default,
  isBefore: require("date-fns/isBefore").default,
  isWithinInterval: require("date-fns/isWithinInterval").default,
  toDate: require("date-fns/toDate").default,
  parse: require("date-fns/parse").default,
  parseISO: require("date-fns/parseISO").default,
  set: require("date-fns/set").default,
  longFormatters: require("date-fns/_lib/format/longFormatters"),
};
